name: Build luci-app-xray Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache libncurses5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 \
          coreutils gawk

      - name: Clone SDK with kernel
        run: |
          git clone --depth=1 -b release https://github.com/madfixed/1806_SDK.git
          cd 1806_SDK/openwrt-18.06
          sed -i 's#git.openwrt.org/feed#github.com/openwrt-mirror#' feeds.conf
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install coreutils
          ./scripts/feeds install gawk

      - name: Add Xray package
        run: |
          cd 1806_SDK/openwrt-18.06
          git clone https://github.com/yichya/luci-app-xray.git package/luci-app-xray

      - name: Configure Build
        working-directory: 1806_SDK/openwrt-18.06
        run: |
          cp target/linux/siflower/sf19a28_rep_fullmask_def.config .config
          echo 'CONFIG_PACKAGE_luci-app-xray=y' >> .config
          echo 'CONFIG_PACKAGE_xray-core=y' >> .config
          echo 'CONFIG_PACKAGE_coreutils=y' >> .config
          echo 'CONFIG_PACKAGE_coreutils-sort=y' >> .config
          echo 'CONFIG_PACKAGE_gawk=y' >> .config
          make defconfig

      - name: Build package
        working-directory: 1806_SDK/openwrt-18.06
        run: |
          make package/luci-app-xray/compile V=s -j$(nproc)
